# Minimal Example: TX Ultimate Easy with Relay Control
# This example shows the simplest possible setup:
# - Button 1 press toggles Relay 1
# - No extra devices or complexity
# - Just the essential touch-to-relay functionality

packages:
  tx_ultimate_easy_minimal:
    url: https://github.com/arieltl/TX-Ultimate-Easy
    ref: main
    refresh: 1min
    files:
      - ESPHome/TX-Ultimate-Easy-ESPHome_minimal.yaml

# Device configuration
substitutions:
  name: tx-minimal-relay
  friendly_name: TX Minimal Relay
  gang_count: '2'  # This will enable Relay 1 and Relay 2 in Home Assistant
  model_format: 'US'

# Override the touch press automation to control relays
# All other automations will use the default behavior (just logging)
tx_ultimate_easy:
  on_press:
    then:
      - lambda: |-
          ESP_LOGI("device", "Button %d pressed at position %d", touch.button, touch.x);
          if (touch.button == 1) {
            ESP_LOGI("device", "Toggling Relay 1");
            output_relay_1->toggle();
          } else if (touch.button == 2) {
            ESP_LOGI("device", "Toggling Relay 2");
            output_relay_2->toggle();
          } else {
            ESP_LOGI("device", "Button %d not configured", touch.button);
          }
