# Minimal Example: TX Ultimate Easy with Relay Control
# This example shows the simplest possible setup:
# - Button 1 press toggles Relay 1
# - No extra devices or complexity
# - Just the essential touch-to-relay functionality

packages:
  tx_ultimate_easy_minimal:
    url: https://github.com/arieltl/TX-Ultimate-Easy
    ref: main
    refresh: 1min
    files:
      - ESPHome/TX-Ultimate-Easy-ESPHome_minimal.yaml

# Device configuration
substitutions:
  name: tx-minimal-relay
  friendly_name: TX Minimal Relay
  gang_count: '3'  # This will enable Relay 1, Relay 2, and Relay 3 in Home Assistant
  model_format: 'US'
  enable_led_feedback: 0  # Disable default LED feedback (we have custom LED control) 

# Override the custom click automations to control relays
# All other automations will use the default behavior (just logging)
tx_ultimate_easy:
  # Customize the long click threshold for this device
  custom_long_click_threshold: 400  # 400ms threshold
  
  # Custom click (short press < 400ms) - toggle relays and flash LED
  on_custom_click:
    then:
      - lambda: |-
          ESP_LOGI("device", "Custom click - Button %d at position %d", touch.button, touch.x);
          if (touch.button == 1) {
            ESP_LOGI("device", "Toggling Relay 1");
            output_relay_1->toggle();
          } else if (touch.button == 2) {
            ESP_LOGI("device", "Toggling Relay 2");
            output_relay_2->toggle();
          } else if (touch.button == 3) {
            ESP_LOGI("device", "Toggling Relay 3");
            output_relay_3->toggle();
          } else {
            ESP_LOGI("device", "Button %d not configured", touch.button);
          }
      - if:
          condition:
            lambda: 'return touch.button == 1;'
          then:
            - light.turn_on:
                id: light_full
                red: 0%
                green: 100%
                blue: 0%
                brightness: 50%
      - if:
          condition:
            lambda: 'return touch.button == 2;'
          then:
            - light.turn_on:
                id: light_full
                red: 0%
                green: 0%
                blue: 100%
                brightness: 50%
      - if:
          condition:
            lambda: 'return touch.button == 3;'
          then:
            - light.turn_on:
                id: light_full
                red: 100%
                green: 100%
                blue: 0%
                brightness: 50%
      - delay: 200ms
      - light.turn_off: light_full

  # Custom long click (long press >= 400ms) - turn off all relays and flash red
  on_custom_long_click:
    then:
      - lambda: |-
          ESP_LOGI("device", "Custom long click - Button %d at position %d", touch.button, touch.x);
          ESP_LOGI("device", "Turning off all relays");
          output_relay_1->turn_off();
          output_relay_2->turn_off();
          output_relay_3->turn_off();
      - light.turn_on:
          id: light_full
          red: 100%
          green: 0%
          blue: 0%
          brightness: 50%
      - delay: 500ms
      - light.turn_off: light_full
